website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, abort
from flask_login import login_required, current_user
from .models import Note
from . import db
import json 
import string, random

characters = list(string.ascii_letters + string.digits + "!@#$%^&*()")
#blueprint for flask app
views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST']) #decorator
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note') #retrieves note from html form
        color = request.form.get('color')
        if len(note) < 2:
            flash('Note is too short', category='error')
        else:
            # new_note = Note(data=note, user_id=current_user.id)
            new_note = Note(data=note, user_id=current_user.id, color=color)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
    
    return render_template("home.html", user=current_user) # allows you to reference current user and check if it is authenticated

@views.route('/update-note-color/<int:note_id>/<string:color>', methods=['POST'])
@login_required
def update_note_color(note_id, color):
    note = Note.query.get_or_404(note_id)
    
    # checking if the note belongs to the current user
    if note.user_id != current_user.id:
        abort(403)
    
    # update note color
    note.color = color
    db.session.commit()
    flash('Note color updated successfully!', category='success')
    
    return redirect(url_for('views.home'))


# @views.route('/edit-note/<int:note_id>', methods=['GET', 'POST'])
# @login_required
# def edit_note(note_id):
#     note = Note.query.get_or_404(note_id)
    
#     if request.method == 'POST':
#         note.data = request.form.get('data')
#         note.color = request.form.get('color') #Updating the color information
#         db.session.commit()
#         flash('Note updated successfully!', category='success')
#         return redirect(url_for('views.home'))
#     return render_template('edit_note.html', note=note)

@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            flash('Note Deleted!', category='success')
        
    return jsonify({})

# Password generation 
@views.route('/popup')
def popup():
    return render_template("popup.html") 

def signup():
    password = request.args.get('password')
    return render_template('signup.html', password=password)

@views.route('/generate-password', methods=['GET', 'POST'])
def generate_password():
    if request.method == 'POST':
        password_length = int(request.form['password_length'])
    else:
        password_length = int(request.args.get('password_length'))
    random.shuffle(characters)
    password = "".join(random.choices(characters, k=password_length))
    return render_template('popup.html', password=password)
    # if password:
    #     return redirect(url_for('auth.sign_up', password=password))
    # else:
    #     return  render_template('popup.html', password=password)    

@views.route('/', methods=['GET', 'POST'])
def index():
   if request.method == 'POST':
       password_length = int(request.form['password_length'])
       password, error = generate_password(password_length)
       if password:
           return render_template('popup.html', password=password, error=None)
       else:
           return render_template('popup.html', password=None, error=error)
   else:
        return render_template('popup.html', password=None, error=None)

@views.route('/regenerate',methods=['POST'])
def regenerate():
    return generate_password()

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <title>{% block title%}Home{% endblock%}</title>

    <link rel="stylesheet" href="../static/style.css" />
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-2">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a href="/" class="nav-item nav-link" id="home">Home</a>
          <a href="/logout" class="nav-item nav-link" id="logout">Logout</a>
          {% else %}
          <a href="/login" class="nav-item nav-link" id="login">Login</a>
          <a href="/sign-up" class="nav-item nav-link" id="signUp">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert">
                        
                        </button>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert">
                        
                        </button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

<div class="container mt-3">
    {% block content %}
    {% endblock %}
</div>

    <!-- <script src="app.js"></script>  -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  

  </body>
</html>

website/templates/home.html
{% extends "base.html" %} 
{% block title%}Home{% endblock%} 
{% block content %}
<h1 align="center" class="fw-bold my-5 py-2">Sticky Notes</h1>
<ul
  class="list-group list-group-flush d-flex flex-row flex-wrap justify-content-evenly"
  id="notes"
>
  {% for note in user.notes %}

  <li
    class="list-group-item d-flex justify-content-between my-2 mx-2 p-3 rounded-5 note-pad" data-unique="{{ note.unique_number}}"
  >
    <div class="color-pick d-flex">
      <ul class="clr-container mt-5 p-0">
        <li class="note-clr clr-pink" data-color="clr-pink"></li>
        <li class="note-clr clr-orange" data-color="clr-orange"></li>
        <li class="note-clr clr-yellow" data-color="clr-yellow"></li>
        <li class="note-clr clr-lightblue" data-color="clr-lightblue"></li>
        <li class="note-clr clr-blue" data-color="clr-blue"></li>
      </ul>
    </div>
    <div class="w-100">
      <span class="me-2">{{ note.data }}</span>
    </div>
    <button
      type="button"
      class="btn-close "
      onClick="deleteNote({{ note.id }})"
    ></button>
  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea
    name="note"
    id="note"
    class="form-control mt-5 mx-2 p-3 rounded-5"
  >
</textarea>
  <br />
  <!-- Below is a hidden input field to store the selected note background color -->
  <input type="hidden" name="color" id="selected-color">
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title%}Log In{% endblock%}

{% block content %}
  <!-- Main Container -->

  <div class="container d-flex justify-content-center align-items-center min-vh-100">
    <!-- Login Container -->

    <div class="row border rounded-5 p-3 bg-white shadow box-area">
      <!-- Left Box -->
      <div class="col-lg-6 col-md-5 rounded-4 d-flex justify-content-center align-items-center flex-column left-box">
          <div class="featured-image my-3">
              <img src="../static/img/1.jpg" alt="Login picture" class="img-fluid rounded-5 login_img_main">
          </div>
          <small class="text-wrap text-center">Join thousands of people saving their notes with us!</small>
      </div>
      
      <!-- Login input -->
      <div class="col-lg-6 col-md-7 right-box">
          <div class="row align-items-center mx-3 px-2">
              <div class="header-text my-4">
                  <h3 class="fw-bold">Welcome</h3>
                  <p class="fsz-8">Enter your details to access your account.
                  </p>
              </div>
              <form method="POST" >
                <div class="form-group mb-2">
                  <label for="email" class="fsz-8">Email Address</label>
                  <input 
                    type="email" 
                    class="form-control"
                    id="email"
                    name="email"
                    placeholder="Enter your email address"
                    />
                </div>
                
                <div class="form-group">
                  <label for="password" class="fsz-8">Password</label>
                  <input 
                    type="password" 
                    class="form-control"
                    id="password"
                    name="password"
                    placeholder="Enter your password"
                    />
                </div>
                <br>
                <button type="submit" class="btn btn-primary w-100 fs-6 my-3 ">Login</button>
                <button class="btn btn-lg btn-light w-100 fs-6"><img src="../static/img/google.png" alt="Google logo" style="width: 20px; height: 20px"> <small class=" me-2">Sign in with google</small></button>
                </form>


              <div class="input-group mt-2 mb-5 d-flex justify-content-between">
                  <div class="form-check">
                      <input type="checkbox" class="form-check-input" id="formCheck">
                      <label for="formCheck" class="form-check-label text-secondary"><p class="fsz-8">Remember Me</p></label>
                  </div>
                  <div class="forgot">
                      <p class="fsz-8"><a href="#">Forgot Password</a></p>
                  </div>
                </div>
              <div class="row">
                  <p class="fsz-8">Dont have an account? <a href="/sign-up">Sign Up</a></p>
              </div>
          </div>

      </div>
    </div>
  </div>

{% endblock %}

website/templates/popup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <title>{% block title%} Password Generator{% endblock%}</title>
    <link rel="stylesheet" href="../static/style.css" />
  </head>

  <body class="mx-0 px-0">
    <div
      class="container d-flex justify-content-center align-items-center min-vh-100 px-0"
    >
      <!-- Popup Container -->

      <div class="row border rounded-5 p-3 bg-white shadow box-area w-100">
        <!-- Left Box -->
        <div
          class="col-md-6 rounded-4 d-flex justify-content-center align-items-center flex-column left-box"
        >
          <div class="featured-image my-3">
            <img
              src="../static/img/password-1.jpg"
              alt="Sign-up"
              class="img-fluid rounded-5 featured-image"
            />
          </div>
        </div>

        <!-- Right Box -->
        <div class="col-md-6 right-box">
          <div class="row align-items-center mx-2">
            <div class="header-text mt-4 mb-5">
              <h3 class="fw-bold">Generate a password</h3>
              <p class="fsz-8">Lets get started.</p>
            </div>
            <div>
              {% if password %}
              <p class="fsz-8">Your password is: <span id="generatedPassword">{{ password }}</span></p>
              <form action="{{ url_for('views.regenerate') }}" method="post">
                <div class="mb-3">
                  <input
                    class="form-control"
                    id="passcode"
                    type="hidden"
                    name="password_length"
                    value="{{ password|length }}"
                  />
                </div>
                <div class="mx-0 px-0">
                    <button type="button" class="btn btn-primary mb-2 w-100" id="use_password">
                        Use Password
                    </button>
                    <button type="submit" class="btn btn-light w-100">
                  Regenerate Password
                    </button>
                    <!--<a href="#" class="clipb_container d-inline btn btn-primary px-1">
                    <i class="bi bi-copy text-light clipboard py-2 px-2"></i>
                    </a>-->
                </div>
                
              </form>
              {% else %}
              <form action="{{ url_for('views.generate_password') }}" method="post" class="my-3">
                <div class="mb-3">
                  <label for="password_length" class="fsz-8"
                    >Enter password length (minimum 6 characters):</label
                  >
                  <input
                    type="number"
                    class="form-control"
                    id="password_length"
                    name="password_length"
                    min="6"
                    required
                  />
                </div>
                <button type="submit" class="btn btn-primary">
                  Generate Password
                </button>
              </form>
              {% endif %} {% if error %}
              <p>{{ error }}</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <script
    type="text/javascript"
    src="{{ url_for('static', filename='index.js') }}"
  ></script>

  </body>
</html>

website/templates/sign_up.html
{% extends "base.html" %} {% block title%}Sign Up{% endblock%}

{% block content %}
<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <!-- Sign Up Container -->

    <div class="row border rounded-5 p-3 bg-white shadow box-area">
      <!-- Left Box -->
      <div class="col-md-6 rounded-4 d-flex justify-content-center align-items-center flex-column left-box">
          <div class="featured-image my-3">
              <img src="../static/img/create-account-1.jpg" alt="Sign-up" class="img-fluid rounded-5  featured-image">
          </div>
      </div>
      
      <!-- Right Box -->
      <div class="col-md-6 right-box">
          <div class="row align-items-center mx-2">
              <div class="header-text mt-4 mb-5">
                  <h3  class="fw-bold">Create an account</h3>
                  <p class="fsz-8 text-body-secondary">Lets get started.
                  </p>
              </div>
              <form method="POST">
                    <div class="form-group mb-3">
                        <label for="email" class="fsz-8">Email Address*</label>
                        <input 
                            type="email" 
                            class="form-control"
                            id="email"
                            name="email"
                            placeholder="email@example.com"
                            />
                    </div>
                    <div class="form-group mb-3">
                        <label for="firstName" class="fsz-8">First Name*</label>
                        <input 
                            type="text" 
                            class="form-control"
                            id="firstName"
                            name="firstName"
                            placeholder="Enter your first name"
                            />
                    </div>
                    <div class="form-group mb-3">
                        <label for="password1" class="fsz-8">Password*</label>
                        <input 
                            type="password" 
                            class="form-control"
                            id="password1"
                            name="password1"
                            placeholder="At least 8 characters"
                            value="{{ password }}"
                            />
                            <p class="fsz-9 text-body-secondary mt-2"> click <a href="#" onClick="genPassword()">here</a> to generate a secure password </p>
                    </div>
                    <div class="form-group mb-3">
                        <label for="password2" class="fsz-8">Confirm Password*</label>
                        <input 
                            type="password" 
                            class="form-control"
                            id="password2"
                            name="password2"
                            placeholder="Confirm your password"
                            />
                            <p class="fsz-9 text-body-secondary mt-2"> By continuing, you agree to the <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a></p>
                    </div>
                    <button type="submit" class="btn btn-primary w-100 fs-6 my-3 ">Submit</button>
                    <button class="btn btn-lg btn-light w-100 fs-6"><img src="../static/img/google.png" alt="Google logo" style="width: 20px; height: 20px"> <small class=" me-2">Sign Up with google</small></button>
            </form>
          </div>

      </div>
    </div>
  </div>
{% endblock %}